# general settings for image SR training
name: SR4_SwinIR_P64W8_DF2K_pretrained
model_type: SRModel
scale: 4
num_gpu: 1
manual_seed: 42

# network structures
network_g:
  type: SwinIR
  in_chans: 3
  img_size: 64
  depths: [ 6, 6, 6, 6, 6, 6 ]
  num_heads: [ 6, 6, 6, 6, 6, 6 ]
  window_size: 8
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  norm_image: true

# path
path:
  pretrain_network_g: pretrain_weights/swin-ir/001_classicalSR_DF2K_s64w8_SwinIR-M_x4.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

  profile_quick:
    start: 0
    frequency: !!float 10e3
    datasets:
      - Set5
      - Set14

  profile_slow:
    start: !!float 10e3
    frequency: !!float 30e3
    datasets:
      - Urban100
      - BSDS100
      # - Manga109


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 30e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - datasets/DF2K/train_HR
    dataroot_lq:
      - datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 24
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training