# general settings for image SR training
name: SR2_KFRN_frozen_SwinIR_Cnd1_rev1
model_type: MultiBranchIRModel
scale: 2
num_gpu: 1
manual_seed: 42

# network structures
network_g:
  type: FusionCompositeModel
  upscale: 2
  channels: 3 # Input Image Channel
  branch: 3 # Branches
  branch_names: ['sr_spatial', 'sr_frequential', 'sr_gan']
  img_range: 1.
  base_model:
    type: MultiBranchSwinIR
    img_size: 64
    depths: [ 3, 3, 4, 4, 3, 3 ]
    num_heads: [ 3, 3, 4, 4, 3, 3 ]
    window_size: 8
    embed_dim: 144
    mlp_ratio: 2
    upsampler: 'pixelshuffle'
    resi_connection: '1conv'
  refinement_model:
    type: KFRNv1
    preprocess: 'none'
    norm_image: true
    difficult_zone_estimator:
      type: DifficultZoneEstimatorV4final
      final_activation: 'none'
      num_block: 4
      expand: 2
    kalman_predictor:
      type: KalmanPredictorMambaBlockV3base
      hidden_channel_expand: 12
      num_layer: 2
      mamba_d_state: 8
      mamba_d_expand: 2.4
      cab_compress_factor: 2
      cab_squeeze_factor: 8
      conv_expand_kernel_size: 3
      conv_expand_norm: 'layer'
      conv_shrink_kernel_size: 1
      final_activation: 'tanh'
    kalman_gain_calculator:
      type: KalmanGainCalculatorV4flexible
      dz_amplify: 3
      dz_amplify_method: 'exp'
      dz_expand: 4.
      img_expand: 5.
      norm_dz_conv_block: 'instance'
      norm_img_conv_block: 'layer'
      activation_dz_conv_block: 'leaky_relu'
      activation_img_conv_block: 'silu'
      merge_expand: 1.2
      norm_merge_conv_block: 'layer'
      activation_merge_conv_block: 'silu'

# path
path:
  pretrain_network_g: experiments/SR2_Baseline_AverageFusion_SwinIR_run0/models/net_g_latest.pth
  strict_load_g: false
  resume_state: ~


# training settings
train:
  frozen_parameters: ['base_model']
  # losses
  mixed_losses:
    type: MixedLoss
    log_gan_output: true
    components:
      loss_main:
        target: 'sr_refined'
        loss:
          type: L1Loss
          loss_weight: 1.0
      loss_auxiliary:
        target: 'difficult_zone'
        mode: 'custom'
        loss:
          type: DifficultZoneReconstructionNoiseLoss
          loss_weight: 0.15
          preprocess: none
          mode: l1

  #  grad_clip_max_norm: !!float 8.00
  optim_g:
    type: Adam
    lr: !!float 6e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 5000

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  enabled_outputs:
    - sr_refined

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

  profile_quick:
    start: 0
    frequency: !!float 10e3
    datasets:
      - Set5
      - Set14

  profile_slow:
    start: !!float 10e3
    frequency: !!float 30e3
    datasets:
      - Urban100
      - BSDS100
      # - Manga109


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 30e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - datasets/DF2K/train_HR
    dataroot_lq:
      - datasets/DF2K/train_LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 24
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/image_SRF_2/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_2/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_2/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_2/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_2/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_2/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_2/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_2/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_2/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_2/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training