# general settings for image SR training
name: KalmanIR_V6_ClassicRun4_pretrained_frozen_DZDCv1_MRSAv2l_KGDCv5e_KPDCv1_run0
model_type: KalmanSRModel
model_output: ['B', 'B', 'B', 'B']
model_output_enabled: [0] # enabled output images
scale: 4
num_gpu: 1
manual_seed: 42

# network structures
network_g:
  type: KalmanIRV6
  upscale: 4
  in_chans: 3
  img_size: 32
  window_size: 8
  img_range: 1.
  d_state: 16
  depths: [ 3, 3, 3, 3, 3, 3 ]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  variant_difficult_zone_estimator: 'deep_convolutional_v1'
  variant_difficult_zone_merge_ratio: 0.2
  variant_uncertainty_estimation: 'mamba_recursive_state_adjustment_v2l'
  variant_gain_calculation: 'deep_convolutional_multiple_channels_v5e'
  variant_gain_calculation_uncertainty_update_ratio: 0.8
  variant_preditor: 'deep_convolutional_v1'

network_d: # Discriminator used in GAN loss
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_d: pretrain_weights/VGGStyleDiscriminator_run1_50000.pth
  pretrain_network_g: experiments/KalmanIR_backbone_stage3_run0/models/net_g_latest.pth
  strict_load_g: false
  resume_state: ~


# training settings
train:
  frozen_module_names_g: ['backbone', 'error_estimation']
  # losses
  losses:
    space_l1:
      mode: 'pixel'
      target: 0
      format: 'D'
      loss:
        type: L1Loss
        loss_weight: 1.0
        reduction: mean
#    fourier_l1:
#      mode: 'pixel'
#      target: 2
#      format: 'D'
#      loss:
#        type: FourierLoss
#        loss_weight: 0.4
#        reduction: mean
#    perceptual:
#      mode: 'perceptual'
#      target: 3
#      format: 'D'
#      loss:
#        type: PerceptualLoss
#        perceptual_weight: 0.4
#        style_weight: 0.0
#        criterion: 'l1'
#        vgg_type: 'vgg19'
#        layer_weights:
#          relu3_3: 1
#    gan:
#      mode: 'gan'
#      target: 3
#      format: 'D'
#      loss:
#        type: GANLoss
#        loss_weight: 0.1
#        gan_type: 'vanilla'


  optim_g:
    type: Adam
    lr: !!float 3e-4
    weight_decay: !!float 1e-7
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 5000

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

  profile_quick:
    start: 0
    frequency: !!float 10e3
    datasets:
      - Set5
      - Set14

  profile_slow:
    start: !!float 10e3
    frequency: !!float 30e3
    datasets:
      - Urban100
      - BSDS100
      - Manga109


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 30e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - datasets/DF2K/train_HR
    dataroot_lq:
      - datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training