# general settings for image SR training
name: MambaIR_pdb_V1_1_test2
model_type: MambaIRModel
scale: 4
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt:
      - /data1/hsw/datasets/DIV2K/DIV2K_train_HR
    dataroot_lq:
      - /data1/hsw/datasets/DIV2K/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: BSDS100
    type: PairedImageDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIR_pdb_V1_1
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  d_state: 16
  depths: [3, 3, 3, 3, 3, 3]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  # for classic SRx4, we use the x2 Model to initialize and halve the training iteration and lr for fast training
  pretrain_network_g: ~ #/data1/guohang/pretrained/SR_MambaIR_x2.pth
  strict_load_g: false
  resume_state: ~ #/home/heshiwen/pyproject/MambaIR/experiments/MambaIR_pd_V2/training_states/15000.state


# training settings
train:
  optim_g:
    type: Adam
    # lr: !!float 2e-4
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    # milestones: [ 250000, 400000, 450000, 475000 ]
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  # total_iter: 500000
  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500