# general settings for image SR training
name: CAR30_Baseline_AverageFusion_SwinIR_run0
model_type: MultiBranchIRModel
scale: 1
num_gpu: 1
manual_seed: 42

# network structures
network_g:
  type: FusionCompositeModel
  upscale: 1
  channels: 1 # Input Image Channel
  branch: 3 # Branches
  branch_names: ['sr_spatial', 'sr_frequential', 'sr_perceptual']
  img_range: 1.
  base_model:
    type: MultiBranchSwinIR
    img_size: 128
    img_range: 1.
    depths: [ 3, 3, 4, 4, 3, 3 ]
    num_heads: [ 3, 3, 4, 4, 3, 3 ]
    window_size: 8
    embed_dim: 144
    d_state: 16
    mlp_ratio: 1.2
    upsampler: 'none'
    resi_connection: '1conv'
    norm_image: true
  refinement_model:
    type: AverageFusion

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~


# training settings
train:
  # losses
  mixed_losses:
    type: MixedLoss
    log_gan_output: true
    components:
      - target: 'sr_refined'
        loss:
          type: CharbonnierLoss
          loss_weight: 1.0
          eps: !!float 1e-5
      - target: 'sr_spatial'
        loss:
          type: L1Loss
          loss_weight: 0.4
      - target: 'sr_frequential'
        loss:
          type: FourierLoss
          loss_weight: 0.4
      - target: 'sr_perceptual'
        name: l1
        loss:
          type: L1Loss
          loss_weight: 0.35
      - target: 'sr_perceptual'
        mode: perceptual
        loss:
          type: PerceptualLoss
          perceptual_weight: 0.1
          layer_weights:
            conv3_1: 1.

  #  grad_clip_max_norm: !!float 8.00
  optim_g:
    type: Adam
    lr: !!float 6e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 5000

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  enabled_outputs:
    - sr_refined
    - sr_spatial
    - sr_frequential
    - sr_perceptual

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

  profile_quick:
    start: 0
    frequency: !!float 10e3
    datasets:
      - Classic5

  profile_slow:
    start: !!float 10e3
    frequency: !!float 30e3
    datasets:
      - LIVE1


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 30e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: CAR
    name: DFWB_CAR
    type: PairedImageDataset
    dataroot_gt: datasets/DFWB_CAR/HQ
    dataroot_lq: datasets/DFWB_CAR/LQ/30
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 24
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Classic5
    type: PairedImageDataset
    task: CAR
    dataroot_gt: datasets/CAR/classic5/Classic5_HQ
    dataroot_lq: datasets/CAR/classic5/Classic5_LQ/30
    filename_tmpl: '{}'
    io_backend:
      type: disk

  val_2:
    name: LIVE1
    type: PairedImageDataset
    task: CAR
    dataroot_gt: datasets/CAR/LIVE1/LIVE1_HQ
    dataroot_lq: datasets/CAR/LIVE1/LIVE1_LQ/30
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500