# general settings for image SR training
name: DichonomySRV8_V2Loss
model_type: MambaIRModel
scale: 4
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - /data1/hsw/datasets/DF2K/train_HR
#      - /data1/hsw/datasets/mini-imagenet/images1
#      - /data1/hsw/datasets/DF2K/train_HR
    dataroot_lq:
      - /data1/hsw/datasets/DF2K/train_LR_bicubic/X4
#      - /data1/hsw/datasets/mini-imagenet/images1_LRx4
#      - /data1/hsw/datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk


    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageShuffleDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageShuffleDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: BSDS100
    type: PairedImageShuffleDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: Urban100
    type: PairedImageShuffleDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageShuffleDataset
    dataroot_gt: /data1/hsw/datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: /data1/hsw/datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: DichotomyIRV8
  upscale: 4
  in_chans: 3
  img_size: 32
  window_size: 8
  img_range: 1.
  d_state: 16
  depths: [3, 3, 3, 3, 3, 3]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  # for classic SRx4, we use the x2 Model to initialize and halve the training iteration and lr for fast training
  pretrain_network_g: ~ #/data1/hsw/pre_train/DichotomyIR/lr_3e_4/models/net_g_latest.pth
  strict_load_g: false
  resume_state: ~ #/home/heshiwen/pyproject/MambaIR-main/experiments/x4_V1_2/training_states/60000.state


# training settings
train:
  optim_g:
    type: Adam
    # lr: !!float 2e-4
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 125000, 200000, 225000, 237500 ]
    # milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  # total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
#    type: L1Loss
#  loss1:
#    type: V3_Loss
#    loss_weight: 1.0
#    reduction: mean
#  loss2:
    type: V2_Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training