# general settings for image SR training
name: KalmanIR_V4_exp_uncertainty_oca_L1_FourierL1_PerceptualL1_GAN
model_type: KalmanSRModel
model_output: ['B', 'B', 'B', 'B']
model_output_enabled: [0, 1] # enabled output images
scale: 4
num_gpu: 1
manual_seed: 42

# network structures
network_g:
  type: KalmanIRV4
  upscale: 4
  in_chans: 3
  img_size: 32
  window_size: 8
  img_range: 1.
  d_state: 16
  depths: [ 3, 3, 3, 3, 3, 3 ]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  uncertainty_estimation_mode: 'oca'
  gain_calculation_mode: ''

network_d: # Discriminator used in GAN loss
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_d: pretrain_weights/msrgan_vgg_discriminator.pth # pretrained MSRGAN Discriminator
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~


# training settings
train:
  # losses
  losses:
    space_l1:
      mode: 'pixel'
      target: 0
      format: 'D'
      loss:
        type: L1Loss
        loss_weight: 1.0
        reduction: mean
    fourier_l1:
      mode: 'pixel'
      target: 2
      format: 'D'
      loss:
        type: FourierLoss
        loss_weight: 0.2
        reduction: mean
#    binary_l1:
#      mode: 'pixel'
#      target: 3
#      format: 'B'
#      loss:
#        type: L1Loss
#        loss_weight: 0.1
#        reduction: mean
#    bce:
#      mode: 'pixel'
#      target: 3
#      format: 'D'
#      loss:
#        type: BCELoss
#        loss_weight: 0.2
#        reduction: mean
#        with_sigmoid: true
    perceptual:
      mode: 'perceptual'
      target: 3
      format: 'D'
      loss:
        type: PerceptualLoss
        perceptual_weight: 0.1
        style_weight: 0.0
        criterion: 'l1'
        vgg_type: 'vgg19'
        layer_weights:
          relu3_3: 1
    gan:
      mode: 'gan'
      target: 3
      format: 'D'
      loss:
        type: GANLoss
        loss_weight: 0.05
        gan_type: 'vanilla'


  optim_g:
    type: Adam
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: -1  # no warm up

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - datasets/DF2K/train_HR
    dataroot_lq:
      - datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training