# general settings for image SR training
name: Discriminator_MultiBranchSwinIR_rgb_pretrain_run0
model_type: DiscriminatorOfflineTrainingModel
scale: 4
num_gpu: 1
manual_seed: 3407

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# network structures
network_g:
  type: FusionCompositeModel
  upscale: 4
  channels: 3 # Input Image Channel
  branch: 3 # Branches
  branch_names: [ 'sr_spatial', 'sr_frequential', 'sr_gan' ]
  img_range: 1.
  base_model:
    type: MultiBranchSwinIR
    img_size: 64
    depths: [ 6, 6, 6, 6, 6, 6 ]
    num_heads: [ 6, 6, 6, 6, 6, 6 ]
    window_size: 8
    embed_dim: 180
    mlp_ratio: 2
    upsampler: 'pixelshuffle'
    resi_connection: '1conv'
    norm_image: true
  refinement_model:
    type: Skipped

# path
path:
  resume_state: ~
  pretrain_network_d: pretrain_weights/msrgan_vgg_discriminator.pth
  strict_load_d: true
  pretrain_network_g: experiments/SR4_MultiBranchSwinIR_branch3_P64W8_DF2K_pretrained_run1/models/net_g_latest.pth
  strict_load_g: true


# training settings
train:
  # losses
  gan_loss:
    type: GANLoss
    gan_type: 'vanilla'
    real_label_val: 1.0
    fake_label_val: 0.0

  # grad_clip_max_norm: !!float 8.00
  optim_d:
    type: Adam
    lr: !!float 3e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  scheduler:
    type: MultiStepLR
    milestones: [ 10000, 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 5000

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  enabled_outputs:
    - sr_spatial
    - sr_frequential
    - sr_gan

  profile_quick:
    start: !!float 10e3
    frequency: !!float 10e3
    datasets:
      - Set5
      - Set14

  profile_slow:
    start: !!float 10e3
    frequency: !!float 30e3
    datasets:
      - Urban100
      - BSDS100
      # - Manga109


# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 20e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~


# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt:
      - datasets/DF2K/train_HR
    dataroot_lq:
      - datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 32
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk


# dist training settings
dist_params:
  backend: nccl
  port: 29500 # general settings for image SR training